//
//  main2.c
//  photometryscript
//
//  Read in a galaxy's statistics file, previously generated by imstatistics,
//  containing image names, modes, and standard deviations. Write out a set of
//  command lines for daofind that can then be run as a script in IRAF.
//

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

int main() {
    
    // Open files as null, sets key parameters.
    FILE *ifile = NULL, *ofile = NULL;
    char  name[30];
    float sky, stddev, minValue;
    int FWHM, sigmaDetect, maxValue;
    double gain, rdnoise, stddevPoisson;
    
    // Open statistics file in reading mode.
    ifile = fopen("stats.list", "r");
    // If statistics file fails to open, prints error message.
    if (ifile == NULL) {
        fprintf(stderr, "Can't open file stats.list for reading\n");
        exit(1);
    }
    
    // Open output file in writing mode.
    ofile = fopen("bootesii.list", "w");
    // If output file fails to open, prints error message.
    if (ifile == NULL) {
        fprintf(stderr, "Can't open file bootesii.list for writing\n");
        exit(1);
    }
    
    // Generates infinite loop to cycle through statistics.
    for(;;) {
        // Reads in image, mode, standard deviation as string and floats.
        fscanf(ifile, "%s%f%f", name, &sky, &stddev);
        // Terminates when end of file is reached.
        if (feof(ifile))
            break;
        // Prints out command line text.
        FWHM = 5;
        sigmaDetect = 4;
        maxValue = 65000;
        gain = 1.4;
        rdnoise = 4.7;
        stddevPoisson = sqrt(sky * 1.4 + pow(rdnoise,2)) / gain;
        minValue = sky - 3 * stddevPoisson;
        fprintf(ofile, "daofind ");
        fprintf(ofile, "%s %i %f %i %f %i \n", name, FWHM, stddevPoisson,
                sigmaDetect, minValue, maxValue);
    }

    // Closes files.
    fclose(ifile);
    fclose(ofile);
}